apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatter-deployment
  labels:
    app: chatter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: chatter
  template:
    metadata:
      labels:
        app: chatter
    spec:
      containers:
        - name: chatter
          image: admin/chatter:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          # Health checks
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # Resource limits
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: chatter-service
  labels:
    app: chatter
spec:
  selector:
    app: chatter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: NodePort