apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatter-deployment
  labels:
    app: chatter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chatter
  template:
    metadata:
      labels:
        app: chatter
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: chatter
          image: placeholder:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: chatter-service
  labels:
    app: chatter
spec:
  selector:
    app: chatter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
      name: http
  type: NodePort