name: Codespace Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build application
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Build Docker image
        run: |
          docker build -t chatter-app .

      - name: Run application
        run: |
          docker run -d -p 8080:8080 --name chatter chatter-app
          sleep 10

      - name: Test application
        run: |
          curl http://localhost:8080/hello